### ISSUE TITLE
open with jupyter lab

### ISSUE THREAD

**Issue by raybellwaves** [NVIDIA/data-science-stack#3]
This is awesome. Thanks for creating. Everything worked great.

I'm fairly new to docker and have a question. Please let me know if you would prefer this go to SO or a forum.

After running `data-science-stack run-container`. It says you can use http://localhost:8888/ to access the jupyer notebook. Is there a command to access jupyter lab to use the lab extension tools that are installed? Currently it says the docker command is `docker run --gpus all --rm -it -p 8888:8888 data-science-stack:2.2.0` not sure if that can be edited to open in jupyter lab?

**Comment by beberg** [comment]
You're right we should be starting jupyter lab by default to take advantage of the already installed extensions. In the next update we'll get that fixed.

In the meantime, start the container and run jupyter-lab:

```bash
docker run --gpus all --rm -it -p 8888:8888 data-science-stack:2.1.0 bash
jupyter-notebook --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token='' --notebook-dir=/notebooks
```
