### ISSUE TITLE
Add storage volume to container

### ISSUE THREAD

**Issue by ncoop57** [NVIDIA/data-science-stack#45]
Hi, my workflow requires adding a data pool as a volume to my containers, e.g.:

```
docker run -v "path/to/data/:/data" ...
```

However, I could find anywhere in your documentation if this is possible. Is there a section about this or is it currently not supported? If it's currently not supported are there any plans to add it?

Any help will be greatly appreciated!

**Comment by flyandlure** [comment]
Yes, I was also a bit confused about how to do this. It would be great if an additional note could be added to the documentation to explain this, please. 

Many thanks,
Matt

**Comment by beberg** [comment]
Will add a section to the README about code and data volumes.

**Comment by flyandlure** [comment]
Many thanks, Beberg. Much appreciated. I managed to do this manually but wasn't sure whether there was a different approach that I should be using. 

`docker run --name nvidia_data_science_stack -v ~/Data/notebooks:/home --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 data-science-stack:2.5.0 `

This maps the directory, but the JupyterLab is set to use the `notebook_dir` of `/notebooks`, which I couldn't seem to override. Appreciate your help with this. 

Thanks,
Matt
